### ISSUE TITLE
Error with setup script that /data disk is missing

### ISSUE THREAD

**Issue by dwakeman** [IBM/hyperledger-fabric-on-linux-one#14]
On several occasions I have seen an error message when running Linux1BlockchainScript.sh where it complains that the /data disk is missing.  It warns me to wait a few minutes and try again.  This seems to be a timing issue of some sort.  It might be worth updating the documentation to let people know it's not a problem.

**Steps to reproduce**

1. Create guest on LinuxOne Community Cloud and login
2. Download the script and change permissions to executable.
3. Run the script.
4. Log out as instructed and then log back in.
5. Run the script again.  

This is where the timing issue comes into play.  I suspect that the first time you run the script it creates the /data directory, but there must be a few seconds of lag before it becomes available.  if you're too fast then you get the error that the /data disk is missing.  If you want 30 seconds and run the script again it seems to work.

**Comment by dconroy** [comment]
+1

**Comment by schellingerhout** [comment]
The issue goes away if waiting for a few seconds and retrying

**Comment by SweetJenn23** [comment]
Thanks! I haven't hit it but you're right @dwakeman .

**Comment by dconroy** [comment]
I am still experiencing this issue regardless of how long I wait. I am using the latest script.

linux1@spotexfabric1:~> ./Linux1BlockchainScript.sh
/data disk is missing. Please wait a moment and try again!


Server details:
Flavor ID:2
Flavor Name:LinuxONE-Medium
VCPUS:2
RAM:4096MB
Root Disk:6GB
Attached Disk:40GB
Image ID:47b7cf72-a399-46fd-aa27-7acfac21b299
Image Name:SLES12 SP2
Description:SpotExchangeFabric1

linux1@spotexfabric1:~> df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        2.0G  8.0K  2.0G   1% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  9.5M  1.9G   1% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/dasda2     5.8G  3.0G  2.6G  54% /
/dev/dasda1     388M   46M  323M  13% /boot/zipl
tmpfs           391M     0  391M   0% /run/user/1001


Can we reopen this issue?

**Comment by likepunk** [comment]
what do you see if you do this?

`$ mount |grep data`

my understanding was /data is provided as default for LinuxONE community server, thus you don't need to create one.

**Comment by dconroy** [comment]
right that what was my understanding as well. seems like the spin up script on the SLES 12 SP2, Linux Medium script might be broken.

The data dir is there when spinning up  SLES 12 SP2 LinuxONE-Small, but not when you spin up  SLES 12 SP2 LinuxONE-Medium. 

Can anyone else confirm?

linux1@medium:~> df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        2.0G  8.0K  2.0G   1% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  9.5M  1.9G   1% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/dasda2     5.8G  3.1G  2.4G  57% /
/dev/dasda1     388M   46M  323M  13% /boot/zipl
tmpfs           391M     0  391M   0% /run/user/1001
linux1@medium:~> mount | grep data
/dev/dasda2 on / type ext4 (rw,relatime,data=ordered)
linux1@medium:~>

**Comment by dconroy** [comment]
the data drive showed up about an hour later...

**Comment by vmorris** [comment]
I can confirm, I noticed this when I went through some early testing. There's some delay between when an instance gets created and the data disk gets attached.

I'm not sure what kind of automation the LinuxONE cloud team put in place to attach these data disks, but it seems to be lagging severely.

**Comment by vmorris** [comment]
Just to clarify @SweetJenn23 and @dwakeman -- it's not the script here that creates the data dir, it's some automation in the LinuxONE provisioning system.

**Comment by cheeye** [comment]
@dconroy @vmorris   Just as @likepunk described, the LinuxONE Community Cloud will do low disk format on a 50GB disk (~42GB usable disk space) and mount the disk to /data. The user directory /data is created by the cloud. So no need to create that directory by your own. 

Because of the low disk format, it will take some time, say 3-5 mins, to complete the format, create a partition, create a file system and mount to /data. But it's definitely abnormal if it takes more than that, like one hour. So I would like to know some details of your Linux instance(s), like ip address. So we can take a look what happened.
