### ISSUE TITLE
The network hlfv1 not exist

### ISSUE THREAD

**Issue by LordwithGlory** [IBM/hyperledger-fabric-on-linux-one#25]
In the tutorial, we can see the **network hlfv1** exists already when we come into xxx.xx.xx.xx:8080(In"Part 2 — Creating a blockchain application and generating API"**_,the picture of STEP 7_**), but when I get into the website, none is here, so we can't do the steps after STEP 51"In the middle of the page".
And I try to ingore this problem, I find  **I can't do the steps after STEP 64**, so how can we solve the problem in this process?

**Comment by LordwithGlory** [comment]
The solution in the pull request I pull [Add the method to create network hlfv1 and add memeber Peeradmin #26](https://github.com/IBM/hyperledger-fabric-on-linux-one/pull/26).

**Comment by erikvaningen** [comment]
I had the same problem. While deploying a new network to hlv1, I got this error:

> An error has occurred
> Error: Error trying login and get user Context. TypeError: this.wallet.contains is not a function
> 

This can be resolved by completely removing all the docker images and the .composer directory. Subsequently run the script Linux1BlockchainScript.sh again (changing 0.17.4 with 0.19.4).

Would this solve your problem?

**Comment by SweetJenn23** [comment]
This has been updated and should be resolved.
