### ISSUE TITLE
Node-red dashboard UI not accessible remotely

### ISSUE THREAD

**Issue by haowangbe** [IBM/hyperledger-fabric-on-linux-one#29]
I'm not able to access the Node-RED dashboard UI. Also the Node-RED UI appears only after refreshing many times my browser. I've tried on different browsers Chrome, Opera, MS Edge, Firefox, Safari with the same problem. Don't see no errors on the server side. In the browser console, I get ...

Application Cache Progress event (12 of 15) http://xxx.xxx.xxx.xxx:1880/ui/font-awesome/fonts/fontawesome-webfont.woff2
xxx.xxx.xxx.xxx/:1 Application Cache Progress event (13 of 15) http://xxx.xxx.xxx.xxx:1880/ui/weather-icons-lite/fonts/weather-icons-lite.woff
xxx.xxx.xxx.xxx/:17 GET http://xxx.xxx.xxx.xxx:1880/ui/js/app.min.js 200 (OK)
xxx.xxx.xxx.xxx/:1 Application Cache Progress event (14 of 15) http://xxx.xxx.xxx.xxx/ui/js/app.min.js
xxx.xxx.xxx.xxx/:1 Application Cache Error event: Resource fetch failed (6) http://xxx.xxx.xxx.xxx:1880/ui/js/app.min.js

**Comment by ztanaka1971** [comment]
I have same issue. Looks like a network problem like before ??

**Comment by SweetJenn23** [comment]
Hi @ztanaka1971, if it's the Composer Playground stuck, then that is potentially a Composer issue. If it is something with Node-RED not necessarily loading that seems to be a undesirable *feature*. I've seen it inconsistently. My only recommendation is to try various browser and clear the cache in the browsers. I seem to have the best luck with Firefox.

**Comment by ztanaka1971** [comment]
@SweetJenn23 , I understand, thank you !

**Comment by SweetJenn23** [comment]
This is being closed.
