### ISSUE TITLE
Not able to install this in local Ubuntu machine

### ISSUE THREAD

**Issue by vishalpatelvc** [IBM/hyperledger-fabric-on-linux-one#30]
Not able to run this file. Linux1BlockchainScript.sh

getting below message everytime.

_PATH was missing '/data/npm/bin'. This has been corrected.
Some changes have been made that require you to log out and log back in.
Please do this now and then re-run this script._

**Comment by silliman** [comment]
This intention of this script is to setup and run on a SLES instance in the LinuxONE Community Cloud, and that instance will have a large file system mounted under /data.  If you wish to use this script to run on your own local machine and in another distro (e.g., Ubuntu in your case) then you will need to customize the script yourself to make it work in your environment.
